
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import * as React from 'react';
import HeaderAppBar from "@/components/layout-components/header-components";
import MuiProvider from "./theme-container";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          style={{backgroundColor: 'white', color: 'black'}}
        >
          <AppRouterCacheProvider>
            {/* <MuiProvider> */}
              <HeaderAppBar /> 
              {children}
            {/* </MuiProvider> */}
          </AppRouterCacheProvider>
          
      </body>
    </html>
  );
}
